### ISSUE TITLE
Example doesn't work with JDK

### ISSUE THREAD

**Issue by firm1** [yaniferhaoui/NordVPN-Public-Java-API#1]
Hello,

When i try your example  (describe on README) code with java request, i get a timeout.

This is my code : 

```java
		try {
			HttpRequest request = HttpRequest.newBuilder()
					.uri(new URI("https://www.monip.org/"))
					.timeout(Duration.of(5, SECONDS))
					.GET()
					.build();

			HttpResponse<String> response = HttpClient
					.newBuilder()
					.proxy(ProxySelector.getDefault())
					.build()
					.send(request, HttpResponse.BodyHandlers.ofString());

			System.out.println(response.body());

		} catch (URISyntaxException e) {
			e.printStackTrace();
		}
```

What i'm doint wrong ?

**Comment by yaniferhaoui** [comment]
Hello @firm1 ,

There are 3 possibilities.

1. Call this code before to perform any HTTP request on your code : 
`System.setProperty("jdk.http.auth.tunneling.disabledSchemes", "");`
(I don't know why, but if you do an HTTP proxy-less request before to call this code, you will not be able to use Proxy JVM system)

2. The problem is maybe come from NordVPN servers which do not support Proxy connections on every servers. So try to do a loop and test with many NordVPN servers. (**This answer seems more likely**)

3. Add more timeout and maybe test this code below instead of my previous example : 
```
String credentials = "YOUR_USERNAME:YOUR_PASSWORD";
String encoded = new String(Base64.getEncoder().encode(credentials.getBytes()));
HttpClient client = HttpClient.newBuilder()
	.connectTimeout(Duration.ofSeconds(60))
        .followRedirects(HttpClient.Redirect.NORMAL)
        .version(HttpClient.Version.HTTP_2)
        .proxy(ProxySelector.of(new InetSocketAddress(NORDVPN_SERVER_DOMAIN, NORDVPN_SERVER_PORT)))
        .build();

// Create Http Request
final HttpRequest httpRequest = HttpRequest.newBuilder()//
	.uri(URI.create("YOUR_TARGET_DOMAIN"))//
        .GET()
        .version(HttpClient.Version.HTTP_2)
        .setHeader("Proxy-Authorization", "Basic " + encoded)
        .build();    
```
